"use strict";

//prettier-ignore
module.exports = {
    welcome: function (mailData) {
        let html = `<table style="background-color: rgb(168, 168, 171); width: 100%; border: 0px;"><tr><td><table  style="background-color: #1c3e99;width: 640px; font-size: 14px; border: 0px; margin:0px auto; background: #1c3e99; border-collapse: collapse;"><tr><td vertical-align="top" style="text-align: center;"><p>&nbsp;</p><a href="https://aiimsrbl.edu.in/"><img width="120px" alt="AIIMS Raebareli LOGO" src="https://aiimsrbl.edu.in/assets/images/brand/aiims.png" class="w_size_1"></a></td></tr><tr><td  vertical-align="top" style="text-align: center;"><h1  style="text-align: center;font-size:22px; font-family:Arial, Helvetica, sans-serif; color:#fff; margin: 2PX; padding: 0PX;">All India Institute of Medical Sciences, Raebareli</h1><p style="font-size:16px; font-family:Arial, Helvetica, sans-serif; color:#fff; padding: 0px; margin: 0px;">Dalmau Road, Munshiganj, Raebareli, Uttar Pradesh. India - 229405<br/><span style="font-size: 14px;">Phone no: +91 0535-2704400 &nbsp;  &nbsp; Email: aiimsrblprogrammer@gmail.com</span></p><p>&nbsp;</p></td></tr><tr><td style="border-top: 1px solid #fff; margin-top: 10px; "><p>&nbsp;</p></td></tr><tr><td style="border:0px ; padding: 20px; background-color: #fff; background: #fff; font-size:14px;"><div style="min-height:500px; background-color: #fff; background: #fff; font-size:14px;"><h1 style="text-align: center;font-size:18px; font-family:Arial, Helvetica, sans-serif; color:#000;">Welcome to Recruitment</h1><p>Dear ${mailData.name} !</p><p>Please click on below link to verify your email. </p><p> <a href="${mailData.emailVerifyLink}">Verify Email</a> </p></div></td></tr><tr><td style="text-align: center; border-top:1px solid #fff; height: 20px; ;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;"><br/><b><a  target="_blank" style="color: #ccc; text-decoration: none;" href="https://www.aiimsrbl.edu.in">www.aiimsrbl.edu.in</a></b><br><b>HELPLINE & SUPPORT</b><br/>Phone no: +91 0535-2704400 &nbsp;&nbsp;&nbsp;  Email: aiimsrblprogrammer@gmail.com</p></td></tr><tr><td style="text-align: center; border-top:1px solid #ccc; height: 50px;;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;">&#169; 2022 AIIMS Raebareli. All Right Reserved.</p></td></tr></table></td></tr></table>`;
        return html;
    },

    resetPassword: function (mailData) {
        let html = `<table style="background-color: rgb(168, 168, 171); width: 100%; border: 0px;"><tr><td><table  style="background-color: #1c3e99;width: 640px; font-size: 14px; border: 0px; margin:0px auto; background: #1c3e99; border-collapse: collapse;"><tr><td vertical-align="top" style="text-align: center;"><p>&nbsp;</p><a href="https://aiimsrbl.edu.in/"><img width="120px" alt="AIIMS Raebareli LOGO" src="https://aiimsrbl.edu.in/assets/images/brand/aiims.png" class="w_size_1"></a></td></tr><tr><td  vertical-align="top" style="text-align: center;"><h1  style="text-align: center;font-size:22px; font-family:Arial, Helvetica, sans-serif; color:#fff; margin: 2PX; padding: 0PX;">All India Institute of Medical Sciences, Raebareli</h1><p style="font-size:16px; font-family:Arial, Helvetica, sans-serif; color:#fff; padding: 0px; margin: 0px;">Dalmau Road, Munshiganj, Raebareli, Uttar Pradesh. India - 229405<br/><span style="font-size: 14px;">Phone no: +91 0535-2704400 &nbsp;  &nbsp; Email: aiimsrblprogrammer@gmail.com</span></p><p>&nbsp;</p></td></tr><tr><td style="border-top: 1px solid #fff; margin-top: 10px; "><p>&nbsp;</p></td></tr><tr><td style="border:0px ; padding: 20px; background-color: #fff; background: #fff; font-size:14px;"><div style="min-height:500px; background-color: #fff; background: #fff; font-size:14px;"><h1 style="text-align: center;font-size:18px; font-family:Arial, Helvetica, sans-serif; color:#000;">Welcome to Recruitment</h1><p>Dear Applicant !</p><p>Please click on below link to reset your password. </p><p> <a href="${mailData.resetLink}">Reset Password</a> </p></div></td></tr><tr><td style="text-align: center; border-top:1px solid #fff; height: 20px; ;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;"><br/><b><a  target="_blank" style="color: #ccc; text-decoration: none;" href="https://www.aiimsrbl.edu.in">www.aiimsrbl.edu.in</a></b><br><b>HELPLINE & SUPPORT</b><br/>Phone no: +91 0535-2704400 &nbsp;&nbsp;&nbsp;  Email: aiimsrblprogrammer@gmail.com</p></td></tr><tr><td style="text-align: center; border-top:1px solid #ccc; height: 50px;;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;">&#169; 2022 AIIMS Raebareli. All Right Reserved.</p></td></tr></table></td></tr></table>`;
        return html;
    },

    changedPassword: function (mailData) {
        let html = `<table style="background-color: rgb(168, 168, 171); width: 100%; border: 0px;"><tr><td><table  style="background-color: #1c3e99;width: 640px; font-size: 14px; border: 0px; margin:0px auto; background: #1c3e99; border-collapse: collapse;"><tr><td vertical-align="top" style="text-align: center;"><p>&nbsp;</p><a href="https://aiimsrbl.edu.in/"><img width="120px" alt="AIIMS Raebareli LOGO" src="https://aiimsrbl.edu.in/assets/images/brand/aiims.png" class="w_size_1"></a></td></tr><tr><td  vertical-align="top" style="text-align: center;"><h1  style="text-align: center;font-size:22px; font-family:Arial, Helvetica, sans-serif; color:#fff; margin: 2PX; padding: 0PX;">All India Institute of Medical Sciences, Raebareli</h1><p style="font-size:16px; font-family:Arial, Helvetica, sans-serif; color:#fff; padding: 0px; margin: 0px;">Dalmau Road, Munshiganj, Raebareli, Uttar Pradesh. India - 229405<br/><span style="font-size: 14px;">Phone no: +91 0535-2704400 &nbsp;  &nbsp; Email: aiimsrblprogrammer@gmail.com</span></p><p>&nbsp;</p></td></tr><tr><td style="border-top: 1px solid #fff; margin-top: 10px; "><p>&nbsp;</p></td></tr><tr><td style="border:0px ; padding: 20px; background-color: #fff; background: #fff; font-size:14px;"><div style="min-height:500px; background-color: #fff; background: #fff; font-size:14px;"><h1 style="text-align: center;font-size:18px; font-family:Arial, Helvetica, sans-serif; color:#000;">Welcome to Recruitment</h1><p>Dear Applicant !</p><p>This is to notify that your password was changed recently for email ${mailData.email}. </p></div></td></tr><tr><td style="text-align: center; border-top:1px solid #fff; height: 20px; ;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;"><br/><b><a  target="_blank" style="color: #ccc; text-decoration: none;" href="https://www.aiimsrbl.edu.in">www.aiimsrbl.edu.in</a></b><br><b>HELPLINE & SUPPORT</b><br/>Phone no: +91 0535-2704400 &nbsp;&nbsp;&nbsp;  Email: aiimsrblprogrammer@gmail.com</p></td></tr><tr><td style="text-align: center; border-top:1px solid #ccc; height: 50px;;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;">&#169; 2022 AIIMS Raebareli. All Right Reserved.</p></td></tr></table></td></tr></table>`;
        return html;
    },

    paymentSuccess: function (mailData) {
        let html = `<table style="background-color: rgb(168, 168, 171); width: 100%; border: 0px;"><tr><td><table  style="background-color: #1c3e99;width: 640px; font-size: 14px; border: 0px; margin:0px auto; background: #1c3e99; border-collapse: collapse;"><tr><td vertical-align="top" style="text-align: center;"><p>&nbsp;</p><a href="https://aiimsrbl.edu.in/"><img width="120px" alt="AIIMS Raebareli LOGO" src="https://aiimsrbl.edu.in/assets/images/brand/aiims.png" class="w_size_1"></a></td></tr><tr><td  vertical-align="top" style="text-align: center;"><h1  style="text-align: center;font-size:22px; font-family:Arial, Helvetica, sans-serif; color:#fff; margin: 2PX; padding: 0PX;">All India Institute of Medical Sciences, Raebareli</h1><p style="font-size:16px; font-family:Arial, Helvetica, sans-serif; color:#fff; padding: 0px; margin: 0px;">Dalmau Road, Munshiganj, Raebareli, Uttar Pradesh. India - 229405<br/><span style="font-size: 14px;">Phone no: +91 0535-2704400 &nbsp;  &nbsp; Email: aiimsrblprogrammer@gmail.com</span></p><p>&nbsp;</p></td></tr><tr><td style="border-top: 1px solid #fff; margin-top: 10px; "><p>&nbsp;</p></td></tr><tr><td style="border:0px ; padding: 20px; background-color: #fff; background: #fff; font-size:14px;"><div style="min-height:500px; background-color: #fff; background: #fff; font-size:14px;"><h1 style="text-align: center;font-size:18px; font-family:Arial, Helvetica, sans-serif; color:#000;">Welcome to Recruitment</h1>`;
        html += `<p>Dear Applicant !</p>`;
        html += `<p>This is to notify that your payment was successful. </p>`;
        html += `<p>Below are the payment details:</p>`;
        html += `<p>`;
        html += `Registration Number: ${mailData.registration_number}<br>`;
        html += `Order Id: ${mailData.razorpay_order_id}<br>`;
        html += `Payment Id: ${mailData.razorpay_payment_id}<br>`;
        html += `Payment Signature: ${mailData.razorpay_signature}<br>`;
        html += `</p>`;
        html += `</div></td></tr><tr><td style="text-align: center; border-top:1px solid #fff; height: 20px; ;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;"><br/><b><a  target="_blank" style="color: #ccc; text-decoration: none;" href="https://www.aiimsrbl.edu.in">www.aiimsrbl.edu.in</a></b><br><b>HELPLINE & SUPPORT</b><br/>Phone no: +91 0535-2700020 &nbsp;&nbsp;&nbsp;  Email: aiimsrblprogrammer@gmail.com</p></td></tr><tr><td style="text-align: center; border-top:1px solid #ccc; height: 50px;;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;">&#169; 2022 AIIMS Raebareli. All Right Reserved.</p></td></tr></table></td></tr></table>`;
        return html;
    },

    editProfile: function (mailData) {
        let html = '';
        html += '<body style="border:1px solid #cdcdcd; width: 800px; margin: 0 auto; font-family: verdana; font-size: 14px;line-height: 15px;">';
        html += '<div>';
        html += '<p style="font-size: 14px; font-weight: 600; font-family: verdana;padding: 10px 10px; line-height: 24px; text-align: center"> ';
        html += `Hi ${mailData.name}!</p>`;
        html += `<p>This is to notify that your profile details was changed recently for email ${mailData.email}. </p>`;
        html += '<p>Team Recruitment</p>';
        html += '</div>';
        return html;
    },

    sendApplicantsEmail: function (mailData) {
        let html = `<table style="background-color: rgb(168, 168, 171); width: 100%; border: 0px;"><tr><td><table  style="background-color: #1c3e99;width: 640px; font-size: 14px; border: 0px; margin:0px auto; background: #1c3e99; border-collapse: collapse;"><tr><td vertical-align="top" style="text-align: center;"><p>&nbsp;</p><a href="https://aiimsrbl.edu.in/"><img width="120px" alt="AIIMS Raebareli LOGO" src="https://aiimsrbl.edu.in/assets/images/brand/aiims.png" class="w_size_1"></a></td></tr><tr><td  vertical-align="top" style="text-align: center;"><h1  style="text-align: center;font-size:22px; font-family:Arial, Helvetica, sans-serif; color:#fff; margin: 2PX; padding: 0PX;">All India Institute of Medical Sciences, Raebareli</h1><p style="font-size:16px; font-family:Arial, Helvetica, sans-serif; color:#fff; padding: 0px; margin: 0px;">Dalmau Road, Munshiganj, Raebareli, Uttar Pradesh. India - 229405<br/><span style="font-size: 14px;">Phone no: +91 0535-2700020 &nbsp;  &nbsp; Email: recruitment@aiimsrbl.edu.in</span></p><p>&nbsp;</p></td></tr><tr><td style="border-top: 1px solid #fff; margin-top: 10px; "><p>&nbsp;</p></td></tr><tr><td style="border:0px ; padding: 20px; background-color: #fff; background: #fff; font-size:14px;"><div style="min-height:500px; background-color: #fff; background: #fff; font-size:14px;"><h1 style="text-align: center;font-size:18px; font-family:Arial, Helvetica, sans-serif; color:#000;">Welcome to Recruitment</h1><p>Dear ${mailData.applicantName} !</p><p>${mailData.emailBody}</p></div></td></tr><tr><td style="text-align: center; border-top:1px solid #fff; height: 20px; ;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;"><br/><b><a  target="_blank" style="color: #ccc; text-decoration: none;" href="https://www.aiimsrbl.edu.in">www.aiimsrbl.edu.in</a></b><br><b>HELPLINE & SUPPORT</b><br/>Phone no: +91 0535-2704400 &nbsp;&nbsp;&nbsp;  Email: aiimsrblprogrammer@gmail.com</p></td></tr><tr><td style="text-align: center; border-top:1px solid #ccc; height: 50px;;"><p style="font-size:14px; font-family:Arial, Helvetica, sans-serif; color:#ccc;">&#169; 2022 AIIMS Raebareli. All Right Reserved.</p></td></tr></table></td></tr></table>`;
        return html;
    },
};
